"""Legal service — SHA-256 hashing and Sec 65B affidavit PDF generation."""

from __future__ import annotations

import hashlib
import io
from datetime import date, datetime, timezone
from pathlib import Path

from fastapi import HTTPException, UploadFile, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.legal import LegalEvent
from app.models.user import User
from app.services.storage_service import upload_file


def compute_sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _generate_affidavit_pdf(event: LegalEvent, user: User) -> bytes:
    """Generate a basic Sec 65B affidavit PDF using ReportLab."""
    try:
        from reportlab.lib.pagesizes import A4  # noqa: PLC0415
        from reportlab.pdfgen import canvas  # noqa: PLC0415
    except ImportError:
        # Fallback: return a plain-text stub
        return (
            f"SECTION 65B AFFIDAVIT\n\n"
            f"Event: {event.title}\n"
            f"Date: {event.incident_date}\n"
            f"SHA-256: {event.video_sha256}\n"
            f"Certified by: MargNetra App\n"
        ).encode()

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 80, "SECTION 65B CERTIFICATE OF ELECTRONIC EVIDENCE")

    c.setFont("Helvetica", 11)
    lines = [
        f"Generated on: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        f"Submitted by: {user.full_name} ({user.phone})",
        f"",
        f"Incident Title : {event.title}",
        f"Incident Date  : {event.incident_date or 'N/A'}",
        f"Location       : {event.location or 'N/A'}",
        f"Description    : {event.description or 'N/A'}",
        f"",
        f"Video URL      : {event.video_url or 'N/A'}",
        f"SHA-256 Hash   : {event.video_sha256 or 'N/A'}",
        f"",
        "I hereby certify under Section 65B of the Indian Evidence Act that the",
        "above electronic record is a true copy of the original and the hash",
        "value above is the integrity fingerprint of the recording.",
        "",
        "This certificate is computer-generated by MargNetra Super App.",
    ]

    y = height - 130
    for line in lines:
        c.drawString(50, y, line)
        y -= 18

    c.save()
    buf.seek(0)
    return buf.read()


async def list_legal_events(
    db: AsyncSession, user: User, offset: int = 0, limit: int = 20
) -> tuple[list[LegalEvent], int]:
    from sqlalchemy import func, desc  # noqa: PLC0415

    count_res = await db.execute(
        select(func.count(LegalEvent.id))
        .select_from(LegalEvent)
        .where(LegalEvent.user_id == user.id)
    )
    total = count_res.scalar_one()
    result = await db.execute(
        select(LegalEvent)
        .where(LegalEvent.user_id == user.id)
        .order_by(desc(LegalEvent.created_at))
        .offset(offset)
        .limit(limit)
    )
    return list(result.scalars().all()), total


async def upload_legal_event(
    db: AsyncSession,
    user: User,
    title: str,
    description: str | None,
    incident_date: date | None,
    location: str | None,
    video_file: UploadFile,
) -> LegalEvent:
    video_bytes = await video_file.read()
    sha256 = compute_sha256(video_bytes)

    video_url = await upload_file(
        data=video_bytes,
        filename=f"legal/{user.id}/{sha256}.mp4",
        content_type=video_file.content_type or "video/mp4",
    )

    event = LegalEvent(
        user_id=user.id,
        title=title,
        description=description,
        incident_date=incident_date,
        location=location,
        video_url=video_url,
        video_sha256=sha256,
        is_certified=True,
    )
    db.add(event)
    await db.commit()
    await db.refresh(event)
    return event


async def export_affidavit(db: AsyncSession, user: User, event_id: int) -> LegalEvent:
    result = await db.execute(
        select(LegalEvent).where(LegalEvent.id == event_id, LegalEvent.user_id == user.id)
    )
    event = result.scalar_one_or_none()
    if not event:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Legal event not found")

    if event.affidavit_pdf_url:
        return event  # Already generated

    pdf_bytes = _generate_affidavit_pdf(event, user)
    pdf_url = await upload_file(
        data=pdf_bytes,
        filename=f"legal/{user.id}/affidavit_{event_id}.pdf",
        content_type="application/pdf",
    )
    event.affidavit_pdf_url = pdf_url
    await db.commit()
    await db.refresh(event)
    return event
